server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 719385414817-se4umhvp5431cfpkn1qrs9k6eil11kt1.apps.googleusercontent.com
            client-secret: omkXNZx3naAOlBaw_FY4W1hz
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          facebook:
            client-id: 374481084238770
            client-secret: 82a7c36f1ba336555216a48e6040a0bf
            scope:
              - email
              - public_profile
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
          naver:
            client-id: IlV4H4WcvJzl5GGAKEke
            client-secret: aYWJxkayEU
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response 라는 키값으로 네이버가 리턴해줌.